package org.apache.cayenne.auto.rati.auto;

/** Class _UsageAssocIpSearch was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UsageAssocIpSearch extends org.apache.cayenne.CayenneDataObject {

    public static final String IP_ID_PROPERTY = "ipId";
    public static final String SEARCH_ID_PROPERTY = "searchId";

    public static final String ID_PK_COLUMN = "ID";

    public void setIpId(Long ipId) {
        writeProperty("ipId", ipId);
    }
    public Long getIpId() {
        return (Long)readProperty("ipId");
    }
    
    
    public void setSearchId(Long searchId) {
        writeProperty("searchId", searchId);
    }
    public Long getSearchId() {
        return (Long)readProperty("searchId");
    }
    
    
}
