package org.apache.cayenne.auto.rati.auto;

/** Class _UsageAssocIpObject was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UsageAssocIpObject extends org.apache.cayenne.CayenneDataObject {

    public static final String IP_ID_PROPERTY = "ipId";
    public static final String OBJECT_PROPERTY = "object";

    public static final String ID_PK_COLUMN = "ID";

    public void setIpId(Long ipId) {
        writeProperty("ipId", ipId);
    }
    public Long getIpId() {
        return (Long)readProperty("ipId");
    }
    
    
    public void setObject(Long object) {
        writeProperty("object", object);
    }
    public Long getObject() {
        return (Long)readProperty("object");
    }
    
    
}
