package org.apache.cayenne.auto.rati.auto;

import java.util.List;

/** Class _Attribute was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Attribute extends org.apache.cayenne.CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String ATTRIBUTES_PROPERTY = "attributes";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void addToAttributes(org.apache.cayenne.auto.rati.Relationship obj) {
        addToManyTarget("attributes", obj, true);
    }
    public void removeFromAttributes(org.apache.cayenne.auto.rati.Relationship obj) {
        removeToManyTarget("attributes", obj, true);
    }
    public List getAttributes() {
        return (List)readProperty("attributes");
    }
    
    
}
