package org.apache.cayenne.auto.rati.auto;

/** Class _UsageSearchLog was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UsageSearchLog extends org.apache.cayenne.CayenneDataObject {

    public static final String SEARCH_TEXT_PROPERTY = "searchText";

    public static final String ID_PK_COLUMN = "ID";

    public void setSearchText(String searchText) {
        writeProperty("searchText", searchText);
    }
    public String getSearchText() {
        return (String)readProperty("searchText");
    }
    
    
}
